variable "user_name" {}
variable "tenant_name" {}
variable "password" {}
variable "auth_url" {}
variable "region" {}
variable "flavor_id" {}
variable "image_id" {}
variable "name_prefix" {}
variable "private_net_id" {}
variable "worker_count" {}
